; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "报表助手"
#define MyAppVersion "1.0.3"
#define MyAppPublisher "广州市每一角落连锁经营管理有限公司"
#define MyAppExeName "GridReportForm.exe"
#define MyAppAssocName MyAppName + ""
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
#define MyAppSetupName "ReportHelperSetup"
#define MyAppDir "..\bin\Release"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DE458FC6-2DE8-4010-B2C7-5DC56EA50484}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
;默认安装目录
DefaultDirName={autopf}\{#MyAppName}
;默认开始菜单名
DefaultGroupName=报表助手
;是否打开->可选安装开始菜单项
AllowNoIcons=yes
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=no
; Uncomment the following line to run in non administrative install mode (install for current user only.)
PrivilegesRequired=admin
OutputBaseFilename={#MyAppSetupName}-{#MyAppVersion}
OutputDir=./{#MyAppVersion}
;安装图标
SetupIconFile={#MyAppDir}\favicon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
;安装需要输入密码
;Password=myjl
;Encryption=yes

;备注版本信息
VersionInfoVersion={#MyAppVersion}
VersionInfoCopyright=Copyright © 2025 每一角落

; SignTool=sha1
; SignedUninstaller=yes

[Languages]
Name: "chinesesimplified"; MessagesFile: "ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone

[Files]
Source: "{#MyAppDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion signonce
Source: "{#MyAppDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
;Source: "{#MyAppDir}\*.ini"; DestDir: "{app}"; Flags: onlyifdoesntexist uninsneveruninstall
;Source: "{#MyAppDir}\*.json"; DestDir: "{app}"; Flags: onlyifdoesntexist uninsneveruninstall
;Source: "{#MyAppDir}\*.db3"; DestDir: "{app}"; Flags: uninsneveruninstall
;Source: "{#MyAppDir}\*.vers"; DestDir: "{app}"; Flags: uninsneveruninstall
Source: "{#MyAppDir}\grdes6.dll"; DestDir: "{app}"; Flags:restartreplace replacesameversion uninsnosharedfileprompt regtypelib regserver
Source: "{#MyAppDir}\gregn6.dll"; DestDir: "{app}"; Flags:restartreplace replacesameversion uninsnosharedfileprompt regtypelib regserver

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon;

;[Code]
;procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
;begin
;if CurUninstallStep = usUninstall then
;  if MsgBox('您是否要删除用户配置信息？', mbConfirmation, MB_YESNO) = IDYES then
    //删除 {app} 文件夹及其中所有文件
;    DelTree(ExpandConstant('{app}'), True, True, True);
;end;



   

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
; Reserve the local device discovery HTTP urlacl (docs/adr/0009) so the helper
; can listen on 127.0.0.1:9294 without elevated privileges at runtime.
Filename: "{sys}\netsh.exe"; Parameters: "http add urlacl url=http://127.0.0.1:9294/ user=Everyone"; Flags: runhidden; StatusMsg: "正在注册本地发现服务端口..."

[UninstallRun]
; Release the discovery urlacl reserved during install.
Filename: "{sys}\netsh.exe"; Parameters: "http delete urlacl url=http://127.0.0.1:9294/"; Flags: runhidden
;Filename: "regsvr32"; Parameters:"""{app}\grdes6.dll"""
;Filename: "regsvr32"; Parameters:"""{app}\gregn6.dll"""

;[UninstallRun]
;Filename: "regsvr32"; Parameters:"/u ""{app}\grdes6.dll"""
;Filename: "regsvr32"; Parameters:"/u ""{app}\gregn6.dll"""
